version: '3.7'

services:
  node_app:
    container_name: node_app
    build: .
    image: tonnyseko/node_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_app_db
      - PG_USER=tonnyseko
      - PG_PASSWORD=postgres
      - PG_HOST=node_db
    depends_on:
      - node_db
    restart: always

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_DB=node_app_db
      - POSTGRES_USER=tonnyseko
      - POSTGRES_PASSWORD=postgres

    volumes:
      - node_db_data:/var/lib/postgresql/data


volumes:
  node_db_data: {}